name: customized_launcher_icons
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.2.0
  image: ^3.0.2
  path: ^1.8.0
  yaml: ^3.1.0


dev_dependencies:
  test: ^1.17.11